version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "8000:80"
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  bot:
    build:
      context: ./bot
    depends_on:
      - web
    env_file:
      - .env